export enum AdActionTypes {
	GET_BRANDS_REQUEST = 'GET_BRANDS_REQUEST',
	GET_MODELS_REQUEST = 'GET_MODELS_REQUEST',
	BRANDS_FETCHED = 'BRANDS_FETCHED',
	MODELS_FETCHED = 'MODELS_FETCHED',
	CAR_LOADED = 'CAR_LOADED',
}
